In [1]:
import numpy as np
import pandas as pd

### Question 1

What's the version of NumPy that you installed?

In [5]:
np.__version__

'1.22.3'

In [6]:
df = pd.read_csv('data.csv')

In [9]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

## 11914 rows

In [102]:
len(df.index)

11914

### Question 3

Who are the most frequent car manufacturers (top-3) according to the dataset?

## Chevrolet, Ford, Volkswagen

In [126]:
top_cars= df.Make.value_counts()
top_cars[:3]


Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4

What's the number of unique Audi car models in the dataset?

## 34

In [104]:
audi_unique_models= df[(df['Make']=='Audi') & (df["Model"])].Model.unique()

In [105]:
audi_unique_models, audi_unique_models.shape

(array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
        'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
        'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
        'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
       dtype=object),
 (34,))

### Question 5

How many columns in the dataset have missing values?

## 6

In [106]:
df.isnull().sum().value_counts().count()

6

Question 6

   * Find the median value of "Engine Cylinders" column in the dataset.
   ## 6  
   
   
   * Next, calculate the most frequent value of the same "Engine Cylinders".
   ## 4.0  
   
   
   
   * Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
   
   ## `filled_col = df['Engine Cylinders'].fillna(4.0)`

   
   * Now, calculate the median value of "Engine Cylinders" once again.
   
   ## 6

   
   * Has it changed?
   
   ## No

In [110]:
# Find the median value of "Engine Cylinders" column in the dataset.
med_val = df['Engine Cylinders'].median()
med_val

6.0

In [135]:
# Next, calculate the most frequent value of the same "Engine Cylinders".
freq_val = df['Engine Cylinders'].mode()
freq_val

0    4.0
Name: Engine Cylinders, dtype: float64

In [123]:
type(freq_val)

pandas.core.series.Series

In [137]:
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value
# from the previous step.

filled_col = df['Engine Cylinders'].fillna(4.0)


In [138]:
filled_col.value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

Question 7

   * Select all the "Lotus" cars from the dataset.
  

   ##  `lotus =df[df['Make']=='Lotus']`
  
  
   * Select only columns "Engine HP", "Engine Cylinders".
   * Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
   
  
   ## `lotus_pd = lotus.loc[:, ["Engine HP", "Engine Cylinders"]].drop_duplicates()
`
   
   
   * Get the underlying NumPy array. Let's call it X.
   
  ## `X = lotus_pd.to_numpy()`
   
   
   * Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
   
   
   ## `TX = X.T`
   ## `XTX = np.dot(TX, X)`
  
  
   * Invert XTX.
   
   
   ## `inverted_XTX = np.linalg.inv(XTX)`
   
   
   * Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
   
  
  ## `y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])`
   
   
   * Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
   
   
   
  ## `bw = np.dot(inverted_XTX, TX)`
  ## `w = np.dot(bw, y)`
    
   * What's the value of the first element of w?
   
   ## `w[0]`==> `4.594944810094551`


In [142]:
# Select all the "Lotus" cars from the dataset.
lotus =df[df['Make']=='Lotus']


In [145]:
# Select only columns "Engine HP", "Engine Cylinders".
lotus_pd = lotus.loc[:, ["Engine HP", "Engine Cylinders"]].drop_duplicates()
lotus_pd

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [148]:
X = lotus_pd.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [155]:
TX = X.T

In [170]:
XTX = np.dot(TX, X)
XTX, XTX.shape

(array([[7.31684e+05, 1.34100e+04],
        [1.34100e+04, 2.52000e+02]]),
 (2, 2))

In [171]:
inverted_XTX = np.linalg.inv(XTX)
inverted_XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [172]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the first element of w?

y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y, type(y), y.shape

(array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800]),
 numpy.ndarray,
 (9,))

In [177]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
bw = np.dot(inverted_XTX, TX)
w = np.dot(bw, y)

In [178]:
# What's the value of the first element of w?
w[0]

4.594944810094551